# Generated by Django 5.0.3 on 2024-04-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='match_info_lst',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='player',
            name='point_lst',
            field=models.JSONField(default=list),
        ),
    ]
