# Generated by Django 5.0.3 on 2024-04-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premier_league', '0002_player_match_info_lst_player_point_lst'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='match_info_lst',
            new_name='match_num_lst',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='point_lst',
            new_name='points_lst',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='point',
            new_name='total_point',
        ),
    ]
